from enum import StrEnum

ADD = '.add'
DELETE = '.delete'
FIELDS = '.fields'
UPDATE = '.update'
TOGGLE_BLOCK_STATUS = '.toggle_block_status'

class InformationEndpoints(StrEnum):
    BLACK_LIST = '/black_list'
    BLACK_LIST_DELETE = BLACK_LIST + DELETE
    BLACK_LIST_ADD = BLACK_LIST + ADD
    BLACK_LIST_TOGGLE_BLOCK_STATUS = BLACK_LIST + TOGGLE_BLOCK_STATUS
    BLACK_LIST_FIELDS = BLACK_LIST + FIELDS
    CLIENTS_ACCOUNTS = '/clients_accounts'
    CLIENTS_ACCOUNTS_UPDATE = CLIENTS_ACCOUNTS + UPDATE
    CLIENTS_ACCOUNTS_FIELDS = CLIENTS_ACCOUNTS + FIELDS
    CLIENTS_ADDRESSES = '/clients_addresses'
    CLIENTS_BONUSES = '/clients_bonuses'
    CLIENTS_BONUSES_ADD = CLIENTS_BONUSES + ADD
    CLIENTS_BONUSES_DELETE = CLIENTS_BONUSES + DELETE
    CLIENTS_BONUSES_FIELDS = CLIENTS_BONUSES + FIELDS